// Renders the files committed on a user's behalf when they hit Deploy.
// Two sets:
//   - User-repo files: Dockerfile + GitHub Actions workflow.
//   - swkoo-kr manifests: namespace, quotas, k8s app resources, metadata.
// Templates inline (rather than read from docs/templates/) so the backend
// image has no filesystem dependency. docs/templates/ remains the human
// onboarding reference; this file is the authoritative source for
// swkoo.kr/deploy auto-onboarding.

export interface RenderParams {
  login: string;
  appName: string;
  imageRepo: string;
  subdomain: string;
  port: number;
  uid: number;
  // "<deployOwner>/<repoName>" — used in the registration file so
  // ApplicationSet knows which repo to pull manifests from.
  deployRepoFullName: string;
  // "<ownerLogin>/<repoName>" — the user's *actual source* repo where
  // their Dockerfile + GHA workflow live. Distinct from deployRepo
  // (Phase 3.1 split). Observatory uses this to resolve the right
  // GitHub Actions runs for a friend's app; without it, the lookup
  // hits the deploy repo and finds no workflows.
  sourceRepo: string;
  // e.g., "apps.swkoo.kr". Pulled from APPS_DOMAIN env so the ingress
  // host doesn't drift from getCurrentDeployment / getDeploymentStatus.
  appsDomain: string;
  // v0 custom domain. Injected by deploy.service when the DB has a row
  // in (applying|active|error-with-applied-commit). When set, the
  // deploy repo emits an extra custom-domain Ingress and adds it to
  // kustomization.yaml. When unset (most callers), no custom resources
  // are emitted — base <slug>.apps.swkoo.kr ingress stays alone.
  customDomain?: { domain: string };
  // Persistent Storage Profile v0. Set when /api/deploy/preview detects
  // a Prisma SQLite app — or when the *existing* metadata.yaml in the
  // control repo already records one (preservation guard in
  // deploy.service.registerForUser). When set:
  //   - <appName>/pvc.yaml is emitted + included in kustomization.
  //   - Deployment strategy flips to Recreate.
  //   - Pod-level fsGroup is added so the runAsUser user can write
  //     to the local-path-provisioned volume.
  //   - An init container runs `prisma migrate deploy` (if
  //     migrations exist) or `prisma db push --skip-generate`.
  //   - DATABASE_URL is set explicitly on app + init containers; it
  //     wins over any value in the envFrom Secret (k8s precedence:
  //     explicit env overrides envFrom on key collision).
  storageProfile?: {
    type: 'prisma-sqlite';
    size: '1Gi';
    mountPath: '/data';
    databaseUrl: 'file:/data/app.db';
    initMode: 'migrate-deploy' | 'db-push';
  };
}

const GENERATED_HEADER =
  '# Generated by swkoo.kr — do not edit; re-deploy from https://swkoo.kr/deploy to regenerate.\n';

/** Single registration file in the control repo (swkoo-kr); read by
 * the ApplicationSet `files` generator. Phase 3.1: one file per user (was a
 * whole directory of manifests). */
export function getUserRegistrationPath(login: string): string {
  return `deploy/users/${login}.yaml`;
}

/** Per-user deploy repo name (inside the deploy org). Stable on re-deploy. */
export function getUserDeployRepoName(login: string): string {
  return login;
}

export function sanitizeName(input: string, maxLength = 53): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLength);
}

export function renderUserRepoFiles(params: RenderParams): Record<string, string> {
  return {
    Dockerfile: renderDockerfile(params),
    '.github/workflows/build.yml': renderBuildWorkflow(params),
  };
}

/** Files committed at the root of `<deployOwner>/<login>` — the per-user
 * deploy repo. ApplicationSet points each Application's source.path at "."
 * so kustomization.yaml at the root references everything.
 *
 * When `params.customDomain` is set, an additional Ingress is emitted at
 * `<appName>/custom-domain-ingress.yaml` and kustomization.yaml includes
 * it. When unset, the file isn't emitted — and the caller must NOT delete
 * an existing one from the deploy repo unless explicitly intending to
 * remove the custom domain (DELETE flow does this via deletePaths). */
export function renderDeployRepoFiles(params: RenderParams): Record<string, string> {
  const files: Record<string, string> = {
    'namespace.yaml': renderNamespace(params),
    'resource-quota.yaml': renderResourceQuota(params),
    'limit-range.yaml': renderLimitRange(params),
    'network-policy.yaml': renderNetworkPolicy(params),
    'role.yaml': renderRole(params),
    'role-binding.yaml': renderRoleBinding(params),
    'kustomization.yaml': renderKustomization(params),
    [`${params.appName}/deployment.yaml`]: renderDeployment(params),
    [`${params.appName}/service.yaml`]: renderService(params),
    [`${params.appName}/ingress.yaml`]: renderIngress(params),
  };
  if (params.customDomain) {
    files[`${params.appName}/custom-domain-ingress.yaml`] = renderCustomDomainIngress({
      login: params.login,
      appName: params.appName,
      domain: params.customDomain.domain,
    });
  }
  if (params.storageProfile) {
    files[`${params.appName}/pvc.yaml`] = renderPvc(params);
  }
  return files;
}

/** Path of the per-app PVC file. Exported for symmetry with
 *  getCustomDomainIngressPath — deploy.service uses it only to
 *  remove the file on un-register (PVC stays unless the whole
 *  deployment is being deleted). */
export function getStoragePvcPath(appName: string): string {
  return `${appName}/pvc.yaml`;
}

/** Path of the custom-domain ingress file. Exported so deploy.service
 * can include/exclude it in the GithubApp.commitFilesAtomic `deletePaths`
 * list when toggling the domain off. */
export function getCustomDomainIngressPath(appName: string): string {
  return `${appName}/custom-domain-ingress.yaml`;
}

/** The registration file the ApplicationSet generator reads. Carries
 * Image Updater values (image.repo, image.updateStrategy) and the
 * pointer (deployRepo) the template substitutes into source.repoURL. */
export function renderUserRegistration(params: RenderParams): string {
  // storage block: only emitted when the app has a profile. The
  // preservation guard in deploy.service reads THIS block back on
  // re-deploy — its presence (regardless of fresh detection) keeps
  // the PVC + mount + init container intact across re-deploys.
  const storageBlock = params.storageProfile
    ? `storage:
  profile: ${params.storageProfile.type}
  size: ${params.storageProfile.size}
  mountPath: ${params.storageProfile.mountPath}
  databaseUrl: ${params.storageProfile.databaseUrl}
  initMode: ${params.storageProfile.initMode}
`
    : '';
  return `${GENERATED_HEADER}login: ${params.login}
appName: ${params.appName}
deployRepo: ${params.deployRepoFullName}
sourceRepo: ${params.sourceRepo}
image:
  repo: ${params.imageRepo}
  updateStrategy: digest
  scanResult: pending
  writeBackMethod: argocd-image-updater
${storageBlock}`;
}

/** Regex parser for the metadata.yaml `storage:` block. Used by the
 *  preservation guard in deploy.service.registerForUser — when
 *  detection returns no profile but the existing metadata says
 *  there's one, the existing values are re-rendered into the next
 *  deploy. Format is controlled by renderUserRegistration above
 *  (shallow, fixed-indent YAML), so a tight regex parser beats
 *  pulling in js-yaml. Returns null on absence or on a profile
 *  this build doesn't recognise. */
export function parseStorageProfileBlock(
  registrationContent: string
): RenderParams['storageProfile'] | null {
  // Capture a `storage:` block: an indented (2-space) line group
  // immediately after the key. Doesn't tolerate tab indent — we
  // emit 2-space.
  const m = registrationContent.match(/^storage:\s*\n((?:[ \t]+.+\n)+)/m);
  if (!m) return null;
  const block = m[1];

  const get = (k: string): string | null => {
    const re = new RegExp(`^\\s+${k}:\\s*(.+)$`, 'm');
    return re.exec(block)?.[1]?.trim() ?? null;
  };
  const profile = get('profile');
  if (profile !== 'prisma-sqlite') return null;

  const size = get('size') ?? '1Gi';
  const mountPath = get('mountPath') ?? '/data';
  const databaseUrl = get('databaseUrl') ?? 'file:/data/app.db';
  const initModeRaw = get('initMode') ?? 'db-push';
  const initMode: 'migrate-deploy' | 'db-push' =
    initModeRaw === 'migrate-deploy' ? 'migrate-deploy' : 'db-push';

  // The literal types on RenderParams.storageProfile are narrow; we
  // cast through `as` once after validating the only field that
  // would mismatch.
  return {
    type: 'prisma-sqlite',
    size: size as '1Gi',
    mountPath: mountPath as '/data',
    databaseUrl: databaseUrl as 'file:/data/app.db',
    initMode,
  };
}

function renderDockerfile(params: RenderParams): string {
  // The template is intentionally Prisma-aware AT THE FILE LEVEL —
  // it adapts at docker build time based on `prisma/schema.prisma`
  // presence, so a single Dockerfile works for both stateless and
  // Prisma-SQLite stacks.
  //
  // Build stage:
  //   - mkdir -p prisma  → ensure the dir exists so the runner COPY
  //     never fails. Empty prisma/ on a stateless app is fine.
  //   - if schema.prisma → npx prisma generate (idempotent; produces
  //     @prisma/client types that the Next build needs).
  // Runner stage:
  //   - apk add openssl  → Prisma's sqlite engine relies on libssl in
  //     some scenarios. ~2 MB on alpine; cheap insurance.
  //   - COPY ./prisma → carries schema + (any) migrations to runtime.
  //     The init container reads them via the user's command — see
  //     renderDeployment.
  //
  // db push / migrate deploy is NEVER run in the build — that requires
  // the runtime PVC mount which only exists once the pod starts.
  return `# Generated by swkoo.kr — do not edit; re-deploy from https://swkoo.kr/deploy.
FROM node:24-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:24-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p public prisma \\
  && if [ -f prisma/schema.prisma ]; then npx --no-install prisma generate; fi \\
  && npm run build

FROM node:24-alpine AS runner
WORKDIR /app
# node:*-alpine ships a 'node' user at uid 1000 — reuse it instead of
# creating a duplicate (adduser would fail with uid conflict).
# openssl is for Prisma's sqlite engine (libssl); harmless on stateless
# apps.
RUN apk add --no-cache tini openssl
ENV NODE_ENV=production PORT=${params.port}
COPY --from=builder --chown=node:node /app/.next ./.next
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/package*.json ./
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/prisma ./prisma
USER node
EXPOSE ${params.port}
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["npx", "next", "start", "-p", "${params.port}"]
`;
}

function renderBuildWorkflow(params: RenderParams): string {
  // Tag with params.imageRepo (already lowercased — DeployService builds
  // it as `ghcr.io/${loginLc}/${repo.toLowerCase()}`) instead of
  // `ghcr.io/${{ github.repository }}`. Docker/GHCR repository names are
  // strictly lowercase; using github.repository preserves the original
  // GitHub casing and breaks `docker/build-push-action` with
  // `invalid tag "ghcr.io/<Owner>/<MixedCase>:<sha>": repository name
  // must be lowercase` for any repo with capital letters (e.g.
  // hatbann/PocketPlan).
  return `# Generated by swkoo.kr — do not edit; re-deploy from https://swkoo.kr/deploy.
name: Build and Push to GHCR

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ${params.imageRepo}:\${{ github.sha }}
            ${params.imageRepo}:latest
`;
}

function renderNamespace(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: Namespace
metadata:
  name: user-${params.login}
  labels:
    swkoo.kr/user: ${params.login}
    swkoo.kr/tenant: user
    # Pod Security Admission, restricted profile, enforced at admission.
    # New pods that don't set seccompProfile / runAsNonRoot / drop ALL
    # capabilities / etc. are rejected outright. The Deployment this
    # template renders is already restricted-compliant (pod-level
    # seccompProfile, automountServiceAccountToken: false, container
    # runAsNonRoot + allowPrivilegeEscalation:false + capabilities.drop
    # ALL). The warn label duplicates the gate at kubectl level for
    # fast feedback when someone hand-edits the deploy repo.
    #
    # Live-verified 2026-05-26 on user-{sungwookoo, sw-koo, hizieun}:
    # all 3 pass server-side dry-run admission. Surgical patch was
    # needed on hizieun's pre-template deployment.yaml — full
    # re-render kept off-limits because of the user's image drift.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
`;
}

function renderResourceQuota(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-${params.login}-quota
  namespace: user-${params.login}
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    requests.storage: "1Gi"
    pods: "3"
    persistentvolumeclaims: "1"
    services: "5"
`;
}

function renderLimitRange(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: LimitRange
metadata:
  name: user-${params.login}-limits
  namespace: user-${params.login}
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 16Mi
`;
}

function renderNetworkPolicy(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-${params.login}-default-deny-egress
  namespace: user-${params.login}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              # RFC1918 private — block lateral movement to cluster internals.
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              # Link-local incl. cloud metadata service (169.254.169.254).
              # Blocks IMDSv1/v2 credential exfil from compromised user pod.
              - 169.254.0.0/16
              # CGN-NAT shared address space — some node networks (OCI, GCP)
              # route control-plane reachable IPs through here.
              - 100.64.0.0/10
              # Loopback — user pods have no business reaching the node's
              # own services via 127.x even if a CNI bug routes it there.
              - 127.0.0.0/8
              # "This host on this network" reserved block.
              - 0.0.0.0/8
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
`;
}

function renderKustomization(params: RenderParams): string {
  const customLine = params.customDomain
    ? `  - ${params.appName}/custom-domain-ingress.yaml\n`
    : '';
  const pvcLine = params.storageProfile
    ? `  - ${params.appName}/pvc.yaml\n`
    : '';
  return `${GENERATED_HEADER}apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - network-policy.yaml
  - role.yaml
  - role-binding.yaml
  - ${params.appName}/deployment.yaml
  - ${params.appName}/service.yaml
  - ${params.appName}/ingress.yaml
${customLine}${pvcLine}`;
}

export interface CustomDomainIngressArgs {
  login: string;
  appName: string;
  domain: string;
}

/** Single source of truth for the custom-domain Ingress YAML. Called
 *  from two places:
 *    - renderDeployRepoFiles, when the user re-deploys and DB has an
 *      applied custom-domain row (preservation guard).
 *    - DomainService.verify, when committing the very first version of
 *      the file after DNS check passes.
 *  Annotation `cert-manager.io/cluster-issuer: letsencrypt-prod`
 *  triggers cert-manager ingress-shim to create a Certificate named
 *  after tls.secretName. HTTP-01 challenge is solved via Traefik.
 *  User namespaces are PSA restricted; cert-manager's solver pod
 *  template is already compliant (spike 0 on 2026-05-26 confirmed). */
/** PersistentVolumeClaim for the per-app /data mount.
 *  - `argocd.argoproj.io/sync-options: Prune=false` — once a stateful
 *    app is registered, ArgoCD must NOT prune this PVC even if it
 *    later appears removed from the desired state by accident.
 *    Deliberate deletion still flows through DeployService.deleteDeployment
 *    which removes the entire registration file → namespace prune
 *    cascades the PVC.
 *  - 1Gi against the namespace ResourceQuota (which allows 1Gi requests.
 *    storage + 1 PVC) — this is the only PVC a user app can claim. */
function renderPvc(params: RenderParams): string {
  if (!params.storageProfile) {
    throw new Error('renderPvc called without storageProfile');
  }
  return `${GENERATED_HEADER}apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${params.appName}-data
  namespace: user-${params.login}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app: ${params.appName}
    swkoo.kr/user: ${params.login}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: ${params.storageProfile.size}
`;
}

export function renderCustomDomainIngress(args: CustomDomainIngressArgs): string {
  return `${GENERATED_HEADER}apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${args.appName}-custom-domain
  namespace: user-${args.login}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    app: ${args.appName}
    swkoo.kr/user: ${args.login}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ${args.domain}
      secretName: ${args.appName}-custom-domain-tls
  rules:
    - host: ${args.domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${args.appName}
                port:
                  number: 80
`;
}

function renderRole(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swkoo-backend-env-manager
  namespace: user-${params.login}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  # Custom domain panel: read the cert-manager Certificate that the
  # custom-domain Ingress provisions. Read-only — cert-manager itself
  # creates and updates the resource. Without this, GET on the domain
  # endpoint falls back to certificateReady=false + lastError.
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list"]
`;
}

function renderRoleBinding(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swkoo-backend-env-manager
  namespace: user-${params.login}
subjects:
  - kind: ServiceAccount
    name: swkoo-backend
    namespace: swkoo
roleRef:
  kind: Role
  name: swkoo-backend-env-manager
  apiGroup: rbac.authorization.k8s.io
`;
}

function renderDeployment(params: RenderParams): string {
  const sp = params.storageProfile;
  // Strategy: stateful → Recreate (single PVC, RWO, single replica
  // means no second pod can attach during a rolling update). Stateless
  // → omit so k8s defaults to RollingUpdate.
  const strategyBlock = sp
    ? `  strategy:
    type: Recreate
`
    : '';
  // Pod-level securityContext gains fsGroup + fsGroupChangePolicy so
  // the non-root container can write to the local-path PV (which is
  // created with root ownership). OnRootMismatch avoids chown'ing
  // every file on each pod start — useful as the DB grows.
  const podSecurityContext = sp
    ? `      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: ${params.uid}
        fsGroupChangePolicy: OnRootMismatch
`
    : `      securityContext:
        seccompProfile:
          type: RuntimeDefault
`;
  // Init container probes prisma/migrations at runtime; the user can
  // add/remove migrations between deploys without us re-templating
  // the YAML. `--no-install` requires Prisma to already be in
  // node_modules (Dockerfile keeps dev deps in the runner so this
  // resolves locally; never reaches out to npm).
  const initContainersBlock = sp
    ? `      initContainers:
        - name: prisma-db-init
          image: ${params.imageRepo}:latest
          imagePullPolicy: Always
          command: ["/bin/sh", "-lc"]
          args:
            - |
              set -e
              if [ -d prisma/migrations ] && [ -n "$(ls -A prisma/migrations 2>/dev/null)" ]; then
                echo "[init] running prisma migrate deploy"
                npx --no-install prisma migrate deploy
              else
                echo "[init] running prisma db push --skip-generate"
                npx --no-install prisma db push --skip-generate
              fi
          env:
            - name: DATABASE_URL
              value: ${sp.databaseUrl}
          volumeMounts:
            - name: app-data
              mountPath: ${sp.mountPath}
          securityContext:
            runAsNonRoot: true
            runAsUser: ${params.uid}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
`
    : '';
  // DATABASE_URL declared via `env:` (NOT envFrom). When both are
  // present k8s gives explicit env precedence on key collision; this
  // is how we keep the platform value authoritative even if the user
  // pastes DATABASE_URL into the env Secret.
  const explicitEnvBlock = sp
    ? `          env:
            - name: DATABASE_URL
              value: ${sp.databaseUrl}
`
    : '';
  const appVolumeMounts = sp
    ? `          volumeMounts:
            - name: app-data
              mountPath: ${sp.mountPath}
`
    : '';
  const volumesBlock = sp
    ? `      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: ${params.appName}-data
`
    : '';

  return `${GENERATED_HEADER}apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${params.appName}
  namespace: user-${params.login}
  labels:
    app: ${params.appName}
    swkoo.kr/user: ${params.login}
spec:
  replicas: 1
${strategyBlock}  selector:
    matchLabels:
      app: ${params.appName}
  template:
    metadata:
      labels:
        app: ${params.appName}
        swkoo.kr/user: ${params.login}
    spec:
      # User pods have no business calling the kube API. The default SA
      # token would otherwise be mounted at /var/run/secrets/... and any
      # process inside the container could use it.
      automountServiceAccountToken: false
      # Pod-level seccomp baseline. RuntimeDefault blocks the riskiest
      # kernel calls (clone3 in old kernels, userfaultfd, etc.) while
      # still allowing every normal HTTP server / Node runtime call.
      # Container's own securityContext below stays as the harder gate.
${podSecurityContext}${initContainersBlock}      containers:
        - name: ${params.appName}
          image: ${params.imageRepo}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: ${params.port}
              name: http
          envFrom:
            # Populated by swkoo.kr/deploy → Environment variables panel.
            # optional:true so the Pod boots before the user sets anything.
            - secretRef:
                name: ${params.appName}-env
                optional: true
${explicitEnvBlock}${appVolumeMounts}          securityContext:
            runAsNonRoot: true
            runAsUser: ${params.uid}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
${volumesBlock}`;
}

function renderService(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: Service
metadata:
  name: ${params.appName}
  namespace: user-${params.login}
  labels:
    app: ${params.appName}
    swkoo.kr/user: ${params.login}
spec:
  selector:
    app: ${params.appName}
  ports:
    - name: http
      port: 80
      targetPort: http
`;
}

function renderIngress(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${params.appName}
  namespace: user-${params.login}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ${params.subdomain}.${params.appsDomain}
      secretName: ${params.appName}-tls
  rules:
    - host: ${params.subdomain}.${params.appsDomain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${params.appName}
                port:
                  number: 80
`;
}
