// Renders the files committed on a user's behalf when they hit Deploy.
// Two sets:
//   - User-repo files: Dockerfile + GitHub Actions workflow.
//   - swkoo-kr manifests: namespace, quotas, k8s app resources, metadata.
// Templates inline (rather than read from docs/templates/) so the backend
// image has no filesystem dependency. docs/templates/ remains the human
// onboarding reference; this file is the authoritative source for
// swkoo.kr/deploy auto-onboarding.

export interface RenderParams {
  login: string;
  appName: string;
  imageRepo: string;
  subdomain: string;
  port: number;
  uid: number;
  // "<deployOwner>/<repoName>" — used in the registration file so
  // ApplicationSet knows which repo to pull manifests from.
  deployRepoFullName: string;
  // "<ownerLogin>/<repoName>" — the user's *actual source* repo where
  // their Dockerfile + GHA workflow live. Distinct from deployRepo
  // (Phase 3.1 split). Observatory uses this to resolve the right
  // GitHub Actions runs for a friend's app; without it, the lookup
  // hits the deploy repo and finds no workflows.
  sourceRepo: string;
  // e.g., "apps.swkoo.kr". Pulled from APPS_DOMAIN env so the ingress
  // host doesn't drift from getCurrentDeployment / getDeploymentStatus.
  appsDomain: string;
  // v0 custom domain. Injected by deploy.service when the DB has a row
  // in (applying|active|error-with-applied-commit). When set, the
  // deploy repo emits an extra custom-domain Ingress and adds it to
  // kustomization.yaml. When unset (most callers), no custom resources
  // are emitted — base <slug>.apps.swkoo.kr ingress stays alone.
  customDomain?: { domain: string };
}

const GENERATED_HEADER =
  '# Generated by swkoo.kr — do not edit; re-deploy from https://swkoo.kr/deploy to regenerate.\n';

/** Single registration file in the control repo (swkoo-kr); read by
 * the ApplicationSet `files` generator. Phase 3.1: one file per user (was a
 * whole directory of manifests). */
export function getUserRegistrationPath(login: string): string {
  return `deploy/users/${login}.yaml`;
}

/** Per-user deploy repo name (inside the deploy org). Stable on re-deploy. */
export function getUserDeployRepoName(login: string): string {
  return login;
}

export function sanitizeName(input: string, maxLength = 53): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLength);
}

export function renderUserRepoFiles(params: RenderParams): Record<string, string> {
  return {
    Dockerfile: renderDockerfile(params),
    '.github/workflows/build.yml': renderBuildWorkflow(params),
  };
}

/** Files committed at the root of `<deployOwner>/<login>` — the per-user
 * deploy repo. ApplicationSet points each Application's source.path at "."
 * so kustomization.yaml at the root references everything.
 *
 * When `params.customDomain` is set, an additional Ingress is emitted at
 * `<appName>/custom-domain-ingress.yaml` and kustomization.yaml includes
 * it. When unset, the file isn't emitted — and the caller must NOT delete
 * an existing one from the deploy repo unless explicitly intending to
 * remove the custom domain (DELETE flow does this via deletePaths). */
export function renderDeployRepoFiles(params: RenderParams): Record<string, string> {
  const files: Record<string, string> = {
    'namespace.yaml': renderNamespace(params),
    'resource-quota.yaml': renderResourceQuota(params),
    'limit-range.yaml': renderLimitRange(params),
    'network-policy.yaml': renderNetworkPolicy(params),
    'role.yaml': renderRole(params),
    'role-binding.yaml': renderRoleBinding(params),
    'kustomization.yaml': renderKustomization(params),
    [`${params.appName}/deployment.yaml`]: renderDeployment(params),
    [`${params.appName}/service.yaml`]: renderService(params),
    [`${params.appName}/ingress.yaml`]: renderIngress(params),
  };
  if (params.customDomain) {
    files[`${params.appName}/custom-domain-ingress.yaml`] =
      renderCustomDomainIngress(params, params.customDomain.domain);
  }
  return files;
}

/** Path of the custom-domain ingress file. Exported so deploy.service
 * can include/exclude it in the GithubApp.commitFilesAtomic `deletePaths`
 * list when toggling the domain off. */
export function getCustomDomainIngressPath(appName: string): string {
  return `${appName}/custom-domain-ingress.yaml`;
}

/** The registration file the ApplicationSet generator reads. Carries
 * Image Updater values (image.repo, image.updateStrategy) and the
 * pointer (deployRepo) the template substitutes into source.repoURL. */
export function renderUserRegistration(params: RenderParams): string {
  return `${GENERATED_HEADER}login: ${params.login}
appName: ${params.appName}
deployRepo: ${params.deployRepoFullName}
sourceRepo: ${params.sourceRepo}
image:
  repo: ${params.imageRepo}
  updateStrategy: digest
  scanResult: pending
  writeBackMethod: argocd-image-updater
`;
}

function renderDockerfile(params: RenderParams): string {
  return `# Generated by swkoo.kr — do not edit; re-deploy from https://swkoo.kr/deploy.
FROM node:24-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:24-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN mkdir -p public && npm run build

FROM node:24-alpine AS runner
WORKDIR /app
# node:*-alpine ships a 'node' user at uid 1000 — reuse it instead of
# creating a duplicate (adduser would fail with uid conflict).
RUN apk add --no-cache tini
ENV NODE_ENV=production PORT=${params.port}
COPY --from=builder --chown=node:node /app/.next ./.next
COPY --from=builder --chown=node:node /app/public ./public
COPY --from=builder --chown=node:node /app/package*.json ./
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
USER node
EXPOSE ${params.port}
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["npx", "next", "start", "-p", "${params.port}"]
`;
}

function renderBuildWorkflow(_params: RenderParams): string {
  return `# Generated by swkoo.kr — do not edit; re-deploy from https://swkoo.kr/deploy.
name: Build and Push to GHCR

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: \${{ github.actor }}
          password: \${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: |
            ghcr.io/\${{ github.repository }}:\${{ github.sha }}
            ghcr.io/\${{ github.repository }}:latest
`;
}

function renderNamespace(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: Namespace
metadata:
  name: user-${params.login}
  labels:
    swkoo.kr/user: ${params.login}
    swkoo.kr/tenant: user
    # Pod Security Admission, restricted profile, enforced at admission.
    # New pods that don't set seccompProfile / runAsNonRoot / drop ALL
    # capabilities / etc. are rejected outright. The Deployment this
    # template renders is already restricted-compliant (pod-level
    # seccompProfile, automountServiceAccountToken: false, container
    # runAsNonRoot + allowPrivilegeEscalation:false + capabilities.drop
    # ALL). The warn label duplicates the gate at kubectl level for
    # fast feedback when someone hand-edits the deploy repo.
    #
    # Live-verified 2026-05-26 on user-{sungwookoo, sw-koo, hizieun}:
    # all 3 pass server-side dry-run admission. Surgical patch was
    # needed on hizieun's pre-template deployment.yaml — full
    # re-render kept off-limits because of the user's image drift.
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
`;
}

function renderResourceQuota(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: ResourceQuota
metadata:
  name: user-${params.login}-quota
  namespace: user-${params.login}
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    requests.storage: "1Gi"
    pods: "3"
    persistentvolumeclaims: "1"
    services: "5"
`;
}

function renderLimitRange(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: LimitRange
metadata:
  name: user-${params.login}-limits
  namespace: user-${params.login}
spec:
  limits:
    - type: Container
      default:
        cpu: 100m
        memory: 128Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 16Mi
`;
}

function renderNetworkPolicy(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: user-${params.login}-default-deny-egress
  namespace: user-${params.login}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              # RFC1918 private — block lateral movement to cluster internals.
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              # Link-local incl. cloud metadata service (169.254.169.254).
              # Blocks IMDSv1/v2 credential exfil from compromised user pod.
              - 169.254.0.0/16
              # CGN-NAT shared address space — some node networks (OCI, GCP)
              # route control-plane reachable IPs through here.
              - 100.64.0.0/10
              # Loopback — user pods have no business reaching the node's
              # own services via 127.x even if a CNI bug routes it there.
              - 127.0.0.0/8
              # "This host on this network" reserved block.
              - 0.0.0.0/8
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80
`;
}

function renderKustomization(params: RenderParams): string {
  const customLine = params.customDomain
    ? `  - ${params.appName}/custom-domain-ingress.yaml\n`
    : '';
  return `${GENERATED_HEADER}apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - network-policy.yaml
  - role.yaml
  - role-binding.yaml
  - ${params.appName}/deployment.yaml
  - ${params.appName}/service.yaml
  - ${params.appName}/ingress.yaml
${customLine}`;
}

function renderCustomDomainIngress(params: RenderParams, domain: string): string {
  // Annotation `cert-manager.io/cluster-issuer: letsencrypt-prod` triggers
  // cert-manager ingress-shim to create a Certificate named after
  // tls.secretName. HTTP-01 challenge is solved via Traefik (same
  // ClusterIssuer the rest of the cluster uses). User namespaces are
  // PSA restricted; cert-manager's solver pod template is already
  // compliant (spike 0 on 2026-05-26 confirmed).
  return `${GENERATED_HEADER}apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${params.appName}-custom-domain
  namespace: user-${params.login}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  labels:
    app: ${params.appName}
    swkoo.kr/user: ${params.login}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ${domain}
      secretName: ${params.appName}-custom-domain-tls
  rules:
    - host: ${domain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${params.appName}
                port:
                  number: 80
`;
}

function renderRole(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: swkoo-backend-env-manager
  namespace: user-${params.login}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  # Custom domain panel: read the cert-manager Certificate that the
  # custom-domain Ingress provisions. Read-only — cert-manager itself
  # creates and updates the resource. Without this, GET on the domain
  # endpoint falls back to certificateReady=false + lastError.
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates"]
    verbs: ["get", "list"]
`;
}

function renderRoleBinding(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: swkoo-backend-env-manager
  namespace: user-${params.login}
subjects:
  - kind: ServiceAccount
    name: swkoo-backend
    namespace: swkoo
roleRef:
  kind: Role
  name: swkoo-backend-env-manager
  apiGroup: rbac.authorization.k8s.io
`;
}

function renderDeployment(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${params.appName}
  namespace: user-${params.login}
  labels:
    app: ${params.appName}
    swkoo.kr/user: ${params.login}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${params.appName}
  template:
    metadata:
      labels:
        app: ${params.appName}
        swkoo.kr/user: ${params.login}
    spec:
      # User pods have no business calling the kube API. The default SA
      # token would otherwise be mounted at /var/run/secrets/... and any
      # process inside the container could use it.
      automountServiceAccountToken: false
      # Pod-level seccomp baseline. RuntimeDefault blocks the riskiest
      # kernel calls (clone3 in old kernels, userfaultfd, etc.) while
      # still allowing every normal HTTP server / Node runtime call.
      # Container's own securityContext below stays as the harder gate.
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: ${params.appName}
          image: ${params.imageRepo}:latest
          imagePullPolicy: Always
          ports:
            - containerPort: ${params.port}
              name: http
          envFrom:
            # Populated by swkoo.kr/deploy → Environment variables panel.
            # optional:true so the Pod boots before the user sets anything.
            - secretRef:
                name: ${params.appName}-env
                optional: true
          securityContext:
            runAsNonRoot: true
            runAsUser: ${params.uid}
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
`;
}

function renderService(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: v1
kind: Service
metadata:
  name: ${params.appName}
  namespace: user-${params.login}
  labels:
    app: ${params.appName}
    swkoo.kr/user: ${params.login}
spec:
  selector:
    app: ${params.appName}
  ports:
    - name: http
      port: 80
      targetPort: http
`;
}

function renderIngress(params: RenderParams): string {
  return `${GENERATED_HEADER}apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${params.appName}
  namespace: user-${params.login}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ${params.subdomain}.${params.appsDomain}
      secretName: ${params.appName}-tls
  rules:
    - host: ${params.subdomain}.${params.appsDomain}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${params.appName}
                port:
                  number: 80
`;
}
